spring:
  application:
    name: @project.build.finalName@

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:quotes_db}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    pl.gozderapatryk.quotesservice: debug

application:
  version: @project.version@
  description: @project.description@

